### ISSUE TITLE
Export and Import Media Events

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#105]
Maupod allows to scan audio files as many times as needed. However events metadata can get lost eventually

To help this process, allow to export/import via ~JSON or~ CSV this information

When importing, choose to overwrite the current events or not

**Comment by Serle66** [comment]
@mauleyzaola I was able to export and import media events with no complications:

### 1. I was able to export media files data multiple times with no problem.

### 2. I exported media events file and Maupod added old records to new records.

![Screen Shot 2020-09-09 at 11 00 12 AM](https://user-images.githubusercontent.com/5943158/92627291-c276cf00-f290-11ea-8cc5-2886a64ed2c0.png)

### I imported media event files from one computer's Maupod to another's computer Maupod, and both files where integrated.

![Screen Shot 2020-09-09 at 11 30 48 AM](https://user-images.githubusercontent.com/5943158/92627711-5cd71280-f291-11ea-84c2-1c8b1c7f264f.png)

![Screen Shot 2020-09-09 at 11 31 33 AM](https://user-images.githubusercontent.com/5943158/92627727-63fe2080-f291-11ea-9ad0-7ac3a98ab360.png)
