### ISSUE TITLE
Preserve track position on restarting Player

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#128]
So, if you'replaying a track and you stop the player, there should be a graceful process, to allow saving somewhere the track position

On restart, the player should put at the top of the queue that track and send a track position command to move it forward where it was playing before being stopped

Blocked by #127

**Comment by Serle66** [comment]
Double checked and everything worked out fine. After stoping the `Player` in the middle of a track and starting the `Player` back again, the track was added to the `Queue` at the same point it has stoped before.
