### ISSUE TITLE
Cache Audio Scan Process

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#135]
Use either redis or an in-memory cache so we ignore files which are recently updated or check the modified date to avoid useless scan process

**Comment by mauleyzaola** [comment]
@Serle66 To test scan one directory and wait until process is completed in the terminal. Then, scan a second time and check this message is present
```
[INFO] no need to scan this file:  /music/2 Eivissa/Are You Ready_/02 Oh La La La.m4a
```
Modify the audio file, like edit the tags (track name for instance)

To make things easier for you, install Kid3: https://prdownloads.sourceforge.net/kid3/kid3-3.8.3-Darwin.dmg?download

Then make another scan of the same directory. This time, since the file has changed after last scan, maupod should detect it and do the actual scan

This message should not be present on this last scan
```
[INFO] no need to scan this file:  /music/2 Eivissa/Are You Ready_/02 Oh La La La.m4a
```

Finally, check the track name you changed with Kid3 is the same in maupod UI

**Comment by Serle66** [comment]
@mauleyzaola Bug report:

- I modified an audio file ussing `Kid3`, change the song's `Tunnel Of Love` TAG name, and scanned the album again.
- On second scan, Maupod should have detected that change and scanned that particular song again, but it din't. The Server window showed the text `[Info] No need to scan this file`, when in fact, it should have.

![Screen Shot 2020-09-06 at 8 10 04 PM](https://user-images.githubusercontent.com/5943158/92340791-4bb7b700-f081-11ea-91b2-93c3bd9e6131.png)

**Comment by mauleyzaola** [comment]
@Serle66 Please give it another try

**Comment by Serle66** [comment]
@mauleyzaola Maupod behave as expected:

1. Empty the music database with `make pg-restore`.
2. Scan one album and highlighted on terminal track 14 `West side Waltz.mp3`.

![Screen Shot 2020-09-25 at 10 01 12 AM](https://user-images.githubusercontent.com/5943158/94285277-13d1c000-ff19-11ea-99a1-2e98a6779cdb.png)

3. Scan the same album for the second time looking on the terminal for: `[INFO] no need to scan this file:  /music-store/You Could Start A Fight in an empty House/14 West Side Waltz.mp3`.

![Screen Shot 2020-09-25 at 10 09 39 AM](https://user-images.githubusercontent.com/5943158/94285343-264bf980-ff19-11ea-816b-30841fca0b52.png)

4. Change `West side Waltz.mp3` track name to `Test for Cache Audio Scan.mp3` using `Kid3`.

![Screen Shot 2020-09-25 at 10 14 01 AM](https://user-images.githubusercontent.com/5943158/94285469-4b406c80-ff19-11ea-9feb-cbfc6f223d44.png)

5. Scan the same album for the third time, and this message was not prsent on the terminal: `[INFO] no need to scan this file:  /music-store/You Could Start A Fight in an empty House/14 West Side Waltz.mp3`.

Maupod did scanned that one track with new name, `Test for Cache Audio Scan.mp3`, and didn't scanned the others, as expected.

![Screen Shot 2020-09-25 at 10 18 46 AM](https://user-images.githubusercontent.com/5943158/94285625-8a6ebd80-ff19-11ea-9144-3f603164f7d5.png)
