### ISSUE TITLE
Unicode File Names are not Scanned

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#138]
```
maupod-restapi_1    | 192.168.0.135 - - [31/Aug/2020:01:19:36 +0000] "POST /file-browser/directory HTTP/1.1" 200 4155 "http://192.168.0.135:9990/file-browser?root=/music/Antonio%20Carlos%20Jobim/Ine%CC%81dito" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"
maupod-audioscan_1  | 2020/08/31 01:19:38 handler_audio_scan.go:27: received audio scan message: root:"/music/Antonio Carlos Jobim/Inédito" scan_date:{seconds:1598836778 nanos:507842751} force:true
maupod-restapi_1    | 192.168.0.135 - - [31/Aug/2020:01:19:38 +0000] "POST /audio/scan HTTP/1.1" 200 22 "http://192.168.0.135:9990/file-browser?root=/music/Antonio%20Carlos%20Jobim/Ine%CC%81dito" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"
maupod-audioscan_1  | 2020/08/31 01:19:38 directory_scan.go:121: [DEBUG] started scanning
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:50: received media info message: file_name:"/music-store/music/Antonio Carlos Jobim/Inédito/01 Wave.flac"
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:62: 
maupod-mediainfo_1  |   : exit status 1
maupod-audioscan_1  | 2020/08/31 01:19:38 directory_scan.go:134: 
maupod-audioscan_1  |   : exit status 1
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:50: received media info message: file_name:"/music-store/music/Antonio Carlos Jobim/Inédito/02 Chega De Saudade.flac"
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:62: 
maupod-mediainfo_1  |   : exit status 1
maupod-audioscan_1  | 2020/08/31 01:19:38 directory_scan.go:134: 
maupod-audioscan_1  |   : exit status 1
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:50: received media info message: file_name:"/music-store/music/Antonio Carlos Jobim/Inédito/03 Sabia.flac"
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:62: 
maupod-mediainfo_1  |   : exit status 1
maupod-audioscan_1  | 2020/08/31 01:19:38 directory_scan.go:134: 
maupod-audioscan_1  |   : exit status 1
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:50: received media info message: file_name:"/music-store/music/Antonio Carlos Jobim/Inédito/04 Samba Do Avião.flac"
maupod-mediainfo_1  | 2020/08/31 01:19:38 handler_media_info.go:62: 
```

**Comment by mauleyzaola** [comment]
@sergio-leyzaola To test this bug is solved, scan any directory which has audio files with spanish names on their files. There should be no error in the terminal

**Comment by Serle66** [comment]
@mauleyzaola Change names to tracks using `Kid3` and `Unicode` characters, and Maupod scanned them perfectly.

First: Finish phrase: `En rakasta sinua enää ollenkaan`

![Screen Shot 2020-09-23 at 7 37 07 PM](https://user-images.githubusercontent.com/5943158/94088442-2099cb00-fdd6-11ea-9cfc-a1a9ad7a4a98.png)
![Screen Shot 2020-09-23 at 7 37 36 PM](https://user-images.githubusercontent.com/5943158/94088459-2abbc980-fdd6-11ea-8069-2c370e1c15c9.png)
![Screen Shot 2020-09-23 at 7 38 49 PM](https://user-images.githubusercontent.com/5943158/94088471-33ac9b00-fdd6-11ea-8766-279cd00e5674.png)
![Screen Shot 2020-09-23 at 7 39 21 PM](https://user-images.githubusercontent.com/5943158/94088560-66ef2a00-fdd6-11ea-8b3d-68cc873cc269.png)

Then, another with the name: `España ñoña`:

![Screen Shot 2020-09-23 at 7 44 51 PM](https://user-images.githubusercontent.com/5943158/94088593-7bcbbd80-fdd6-11ea-839d-3f28995fd180.png)
![Screen Shot 2020-09-23 at 7 45 19 PM](https://user-images.githubusercontent.com/5943158/94088602-81c19e80-fdd6-11ea-88d3-6e5385b38f12.png)
![Screen Shot 2020-09-23 at 7 46 26 PM](https://user-images.githubusercontent.com/5943158/94088609-87b77f80-fdd6-11ea-9913-09e48001d067.png)
![Screen Shot 2020-09-23 at 7 46 55 PM](https://user-images.githubusercontent.com/5943158/94088623-8f772400-fdd6-11ea-9c1d-5415f9cab4c8.png)

Server didn't had error and there was no problem with the scanning in both cases.
