### ISSUE TITLE
Spectrum Image width should match browser

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#142]
Currently spectrum size is hardcoded to 1920 pixels width. It should take the width of the browser dynamically

~For this to be fixed we need to subscribe to the event in the browser and re-generate a new spectrum image from the backend~

When the control has been loaded, ask the backend for the spectrum, given the width of the browser at that moment. The height should be provided as well, however this can be a constant in the frontend (there is already a constant for that)

The backend should support parameters for image generation, now it is hardcoded too

References from the code:

https://github.com/mauleyzaola/maupod/blob/687e10c2a42d588da68665ef653dd29f385f2cd6/ui-player/src/components/TrackControl.js#L56-L62

https://github.com/mauleyzaola/maupod/blob/6f6b4b402756b758050f1a633e17d63bd2dd8c5a/ui-player/src/canvas.js#L2

https://github.com/mauleyzaola/maupod/blob/9f22fa010299fc12d742bbbf09a57cb716d9b187/src/cmd/mediainfo/handler_spectrum_generate.go#L52-L92

## 1920x1080

![image](https://user-images.githubusercontent.com/1648558/92550483-2a8dcc80-f221-11ea-8f97-a9f9d137a3e3.png)

## 1680x1050

![image](https://user-images.githubusercontent.com/1648558/92550548-57da7a80-f221-11ea-9e62-aafc635828a8.png)

## 1440x900

![image](https://user-images.githubusercontent.com/1648558/92550589-72acef00-f221-11ea-8168-2e7ffe581ee6.png)

## 1024x768

![image](https://user-images.githubusercontent.com/1648558/92550622-8ce6cd00-f221-11ea-9fef-c7c8ff50e5ea.png)

**Comment by mauleyzaola** [comment]
@ismaelchess Made some changes in the scope, to simplify this issue. Let me know if all makes sense to you

**Comment by Serle66** [comment]
@mauleyzaola Spectrum Image draws on demand all right.

![spectrum-drwas-on-demand](https://user-images.githubusercontent.com/5943158/93719518-aaccff80-fb48-11ea-9a35-9b409beb5ca4.gif)
