### ISSUE TITLE
Recorded Date not being parsed with invalid dates

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#143]
Sometimes we have the `recorded_date` field mode media info in this format
```
mau@amd7:Arrival$ mediainfo -f 01\ Mosquito\ Bite.m4a | grep -i recorded 
Recorded date                            : UTC 2007-08-09 07:00:00
```

We could simply remove the leading prefix and parse as date the rest. If success, consider it the valid one

**Comment by mauleyzaola** [comment]
@Serle66 Please double check. Thanks

**Comment by Serle66** [comment]
The recording date appears correctly

![Screen Shot 2020-10-07 at 12 36 13 PM](https://user-images.githubusercontent.com/5943158/95368011-1fb76d80-089b-11eb-9b3a-1d53c9fa5a2b.png)
