### ISSUE TITLE
Swagger Documentation

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#172]
The list of endpoints is becoming larger, so it may be a good idea to start documenting those with Open API

These are the current endpoints we need to document in Swagger. Ping is already done as an example

https://github.com/mauleyzaola/maupod/blob/6fbb2589724658f4d5fac5d387e1ff91d0c239e3/src/cmd/restapi/pkg/api/router.go#L24-L48

Swagger is Open API 3.0: https://www.openapis.org/

To open the swagger ui page and test it, run these commands from `src/`
```
make server
```
Once server is up, in another terminal
```
make swagger
```

The Swagger definitions are in this file: https://github.com/mauleyzaola/maupod/blob/master/src/docs/swagger/endpoints.yml

You can edit the file, save and refresh the UI. Changes should be there. Check the console for errors, if any

Once this task is completed we *must* update the swagger file with the code as it changes

**Comment by mauleyzaola** [comment]
@Serle66 Please verify this is working

In one terminal `make server`

In another `make browser`

In another `make swagger`. This will open a new tab in the browser with swagger. Play with all the items in `playlist` section and make sure they work as expected.

*NOTE*: when you supply `media` object it is not needed to pass all the fields, only the `id` of the media is needed

![image](https://user-images.githubusercontent.com/1648558/94569809-c06eb300-0233-11eb-8288-b49edeeac1aa.png)

**Comment by Serle66** [comment]
@mauleyzaola the `Swagger` items review was 90% successful, just one bug.

## 1. `DELETE` /playlists/{id}

Several playlists were successfully removed.

![Screen Shot 2020-09-29 at 1 13 18 PM](https://user-images.githubusercontent.com/5943158/94609547-8f5aa680-0264-11eb-83fd-c9c123637967.png)

`Swagger` returned no errors.

![Screen Shot 2020-09-29 at 1 14 08 PM](https://user-images.githubusercontent.com/5943158/94609930-1e67be80-0265-11eb-8705-6629ebfb39a4.png)

## 2. `PUT` /playlists/{id}

Every attempt to change a playlist's name was successful.

#### Very long name:

![Screen Shot 2020-09-29 at 1 17 08 PM](https://user-images.githubusercontent.com/5943158/94610213-8b7b5400-0265-11eb-9cdf-846209c32212.png)

#### Even using weird characters and languages:

![Screen Shot 2020-09-29 at 1 25 00 PM](https://user-images.githubusercontent.com/5943158/94610596-2411d400-0266-11eb-9afb-08e82850382e.png)

#### Numbers, letters and characters (last one):

![Screen Shot 2020-09-29 at 1 28 46 PM](https://user-images.githubusercontent.com/5943158/94610698-4ad00a80-0266-11eb-9341-7da9d1075f2c.png)

## 3. `GET`  /playlists/{id}

Every attempt was successful.

![Screen Shot 2020-09-29 at 1 22 27 PM](https://user-images.githubusercontent.com/5943158/94610852-85d23e00-0266-11eb-9583-f89528f115da.png)

## 4. `POST` /playlists

I was able to create as many playlists as I wanted, and there was no problem with names, characters, length or numbers.

![Screen Shot 2020-09-29 at 1 22 35 PM](https://user-images.githubusercontent.com/5943158/94611184-fc6f3b80-0266-11eb-8926-02e5e8485a65.png) 

## 5. `GET` /playlists

This item showed the content of a playlist every time, and it was successfully updated after adding new `media` or been edited several times. 

![Screen Shot 2020-09-29 at 1 40 33 PM](https://user-images.githubusercontent.com/5943158/94611406-4d7f2f80-0267-11eb-963e-43d1409ea0f5.png)

## 6. `PUT` /playlists/{id}/items

Swagger return error: #181 

![Screen Shot 2020-09-29 at 2 03 25 PM](https://user-images.githubusercontent.com/5943158/94609306-2e32d300-0264-11eb-967a-716fbb50dd40.png)

## 7. `POST` /playlists/{id}/items

Every attempt to add new `Media` into a `Playlist` was successful.

![Screen Shot 2020-09-29 at 1 38 44 PM](https://user-images.githubusercontent.com/5943158/94611594-91723480-0267-11eb-8b0f-09347ebc8221.png)

![Screen Shot 2020-09-29 at 1 39 31 PM](https://user-images.githubusercontent.com/5943158/94611608-96cf7f00-0267-11eb-9814-91cfee20de0b.png)

![Screen Shot 2020-09-29 at 1 40 33 PM](https://user-images.githubusercontent.com/5943158/94611624-9cc56000-0267-11eb-9b36-d57c530cbd14.png)

## 8. `GET` /playlists/{id}/items

This item showed all playlist's `Media` content, even after adding new tracks to it or removing them. It was always updated without errors.

![Screen Shot 2020-09-29 at 1 43 04 PM](https://user-images.githubusercontent.com/5943158/94611912-00e82400-0268-11eb-9bb5-4c227564abb4.png)

## 9. `DELETE` /playlists/{id}/items/{position}

I was able to delete several tracks and the `Playlist` ordered it's `Media` accordingly, without messing up the rest of the tracks positions.

I even added the same track `Six Blades Knife` in `0, 3, 5` positions, deleted number `3` and the play list reordered it's tracks positions accordingly, leaving the song twice in the list, in positions `0` and `4`
