### ISSUE TITLE
Failed Uploading Album Cover from Album View

### ISSUE THREAD

**Issue by Serle66** [mauleyzaola/maupod#175]
Reference: #119 

After acquiring Token at `Discogs api`,  Maupod failed any attempts to upload album covers:

![covers-bug](https://user-images.githubusercontent.com/5943158/94085412-a9f8cf80-fdcd-11ea-8810-3f17ed76068b.gif)

Other example:

![Screen Shot 2020-09-23 at 6 30 55 PM](https://user-images.githubusercontent.com/5943158/94085823-c34e4b80-fdce-11ea-9b2a-e771185f46b9.png)

And it was't a case of wrong size, but a `ok, false, error, nats, time out` issue.

![Screen Shot 2020-09-23 at 6 29 38 PM](https://user-images.githubusercontent.com/5943158/94085897-fbee2500-fdce-11ea-9b2d-0c53cf1acc4b.png)

**Comment by Serle66** [comment]
@mauleyzaola Apparently, the problem only occurs when you want to replace an existing cover art, because it works fine when the album does not have one and you simply add it for the first time.

![bug-cover-02](https://user-images.githubusercontent.com/5943158/94087199-cba88580-fdd2-11ea-9071-a78d11c99885.gif)

**Comment by mauleyzaola** [comment]
@Serle66 Cannot reproduce this anymore with the button
