### ISSUE TITLE
Playlist Swagger Error `PUT /playlists/{id}/items`

### ISSUE THREAD

**Issue by Serle66** [mauleyzaola/maupod#181]
Reference: #172 

Playlist item `PUT /playlists/{id}/items` returns error after any attempt of changing items positions on playlist:

![Screen Shot 2020-09-29 at 2 03 25 PM](https://user-images.githubusercontent.com/5943158/94604047-ba40fc80-025c-11eb-9ae3-36c8cf91574a.png)

The solution could come by adding `{position}` at the `PUT /playlists/{id}/items` URL, same as `DELETE /playlists/{id}/items/{position}`.

![Screen Shot 2020-09-29 at 2 09 22 PM](https://user-images.githubusercontent.com/5943158/94605454-c0d07380-025e-11eb-8829-8ea78ceee3a1.png)

That way, the URL will take the new media position, and the request would be: "look for the `media X` with `ID X`, occupying `position X`, and placed in a new position, which will be located at the new URL `{position}`".

The problem is, right now you are telling which item is the one to be changed, but you are not telling where you want it to be next.

**Comment by mauleyzaola** [comment]
@Serle66 Please double check in swagger everything works as expected. Thanks

**Comment by Serle66** [comment]
@mauleyzaola I've double checked every item and there where no more errors.

- [ ] DELETE /playlists/{id}
- [ ] PUT /playlists/{id}
- [ ] GET /playlists/{id}
- [ ] POST /playlists
- [ ] GET /playlists
- [ ] POST /playlists/{id}/items
- [ ] GET /playlists/{id}/items
- [ ] PUT /playlists/{id}/items/{position}
- [ ] DELETE /playlists/{id}/items/{position}
