### ISSUE TITLE
Add Total Time for a Queue List

### ISSUE THREAD

**Issue by Serle66** [mauleyzaola/maupod#209]
Maybe it would be a good idea to add a `Total Time` for a `Queue List`, in case the user needs to plan in advance for a determined time period. That way, the user won’t be forced to do math impromptu.

- The `Total Time` would have to change as the tracks are played.
- Maybe, the `Total Time` can be displayed along with the `Queue List` cover.

**Comment by mauleyzaola** [comment]
Millisecond precision is causing an offset. Need to truncate to seconds from the server
![image](https://user-images.githubusercontent.com/1648558/100295983-a827c580-2f50-11eb-89c5-98a305219aaa.png)

**Comment by Serle66** [comment]
After several tracks added and deleted, the `Total Time` was accurate and Maupod didn't added that second extra.
