### ISSUE TITLE
Cannot browse to another album while in the album view

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/maupod#212]
Steps to reproduce:
* Play a song
* Open any album, different than the one you're listening to
* Click on the album in the player section, url changes in the browser but UI doesn't do anything

**Comment by Serle66** [comment]
I was able to browse from album to album and play new tracks every time when one song was playing already.

![browse-to-another-album](https://user-images.githubusercontent.com/5943158/97377916-bb2e7380-1886-11eb-935f-f6b7d883ac0a.gif)
